### ISSUE TITLE
用了您的Tiny-Alert，提几点建议

### ISSUE THREAD

**Issue by hello-lizhihua** [shootyou/Tiny-Alert#2]
1..rDialog设置字号大小，比如font-size: 20px，因为您写的弹框中有em单位的存在，我们的移动是使用rem，会根据屏幕宽度计算html的字号大小，例如360px宽度屏幕，对应html{font-size:36px;}。所以弹框会显得很大
2..rDialog-wrap的透明度建议由opacity:0.7改为background: rgba(0,0,0,0.7)，现在整体透明很不美观。

**Comment by shootyou** [comment]
感谢建议，可以直接提交代码，我合并进去。
